apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyponome-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: ghcr.io/hnrkndrssn/Hyponome
          ports:
            - containerPort: 5000
              name: http-port
            - containerPort: 5001
              name: https-port
