name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

  OCTOPUS_URL: ${{ vars.SERVER }}
  OCTOPUS_API_KEY: ${{ secrets.API_KEY }}
  OCTOPUS_SPACE: ${{ vars.SPACE }}

jobs:
  calculate-version:
    runs-on: ubuntu-latest

    outputs:
      app_version: ${{ steps.calculate_version.outputs.octoversion_fullsemver }}
      app_info_version: ${{ steps.calculate_version.outputs.octoversion_informationalversion }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install OctoVersion
        run: |
          dotnet tool install OctoVersion.Tool

      - name: Calculate Version
        id: calculate_version
        run: |
            dotnet tool run octoversion --CurrentBranch=${{ github.head_ref || github.ref }} --Patch ${{ github.run_number }} --DetectEnvironment true
            echo $OCTOVERSION_FullSemVer
            echo $OCTOVERSION_InformationalVersion
  
  build-and-push-image:
    runs-on: ubuntu-latest    
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    needs: calculate-version
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          context: .
          file: docker/Dockerfile
          build-args: |
            APP_VERSION=${{ needs.calculate-version.outputs.app_version }}
            APP_INFO_VERSION=${{ needs.calculate-version.outputs.app_info_version }}
          push: ${{ github.event_name != 'pull_request' }}  
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
